project:
  type: website
  output-dir: docs

website:
  title: "Tassilo Heinrich"
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - href: index.qmd
        text: About 
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/tazheinrich
        aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com/in/tassilo-heinrich-56692513b/
        aria-label: Linkedin
      - icon: twitter
        href: https://twitter.com/tazheinrich
        aria-label: Twitter

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



