project:
  type: website
  output-dir: docs

website:
  title: "Tassilo Heinrich"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: test

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



